config/routes.rb
AccountManager::Application.routes.draw do
  resources :cashflows
  resources :clients
  devise_for :users
  root :to => 'application#index'
  get 'show_image/:id' => 'user_profile#show_image'
  get 'user_profile/index'
  
  match '/setting' => "user_profile#edit", :as => :profile ,via: [:get, :patch]
  match 'profile/edit' => "user_profile#update", via: [ :put, :patch ], :as => :update_profile
  match 'profile/update_password'=> "user_profile#update_password", via: [:patch],:as => :update_password
  match 'profile/update_secret_password' => 'user_profile#update_secret_password', via: [:patch], :as => :update_secret_password

  match 'client_cash_flow_detail/:id' => "clients#cashflow_detail", via: [:get], :as => :cashflow_detail
  
  # Search route
  get 'search/new'
  match 'search/generate_report'=> "search#generate_report", via: [:post],:as => :generate_report


  match 'new_cashflow_credit'=>"cashflows#new",via: [:get],:as => :new_cashflow_credit
  match 'new_cashflow_debit'=>"cashflows#new",via: [:get],:as => :new_cashflow_debit


  #  Delete Validation Path
  match '/confirmation_secrate' => 'application#confirmation_secrate', :as => "confirmation", via: [:get]
  match '/confirmation_sec' => 'clients#confirmation_secrate', :as => "confirmation_cash", via: [:get]

  match '/confirmation_delete' => 'clients#confirmation_delete', :as => "confirmation_delete", via: [:get]
  match '/confirmation_cash_delete' => 'cashflows#confirmation_cash_delete', :as => "confirmation_cash_delete", via: [:get]

  
end

app/views/layouts/shared/_content.html.erb
<div id="head-nav" class="navbar navbar-default" style="height: 56px;">
  <div class="container-fluid">
    <div class="navbar-collapse">
      <% if mobile_device? %>
        <ul class="nav navbar-nav navbar-right user-nav">
          <li class="dropdown profile_menu">
            <% if !current_user.profile_pic_data.nil? %>
              <a href="#" class="dropdown-toggle" data-toggle="dropdown"><%= image_tag url_for(:action => 'show_image',:controller => "user_profile" , :id => current_user.id), :size => "32x32" %>
                <span>
                  <% if !current_user.first_name.blank? %>
                    <%= current_user.first_name%>&nbsp<%= current_user.last_name%>
                  <% else %>
                    <%= current_user.email %>
                  <% end %>
                </span> <b class="caret"></b>
              </a>
              <% else %>
                <a href="#"><img alt="Avatar" src="/assets/avatar6.jpg" style="height: 30px;">
                  <span>
                    <% if !current_user.first_name.blank? %>
                      <%= current_user.first_name%>&nbsp<%= current_user.last_name%>
                    <% else %>
                      <%= current_user.email %>
                    <% end %><b class="caret"></b>
                  </span>
                </a>
              <% end %>
            <ul class="dropdown-menu" style ="margin-top: 0px !important; background-color: #DACCF8 !important">
              <li><%= link_to "Setting",profile_path %></li>
              <li><%= link_to "Log out",destroy_user_session_path, method: :delete %></li>
            </ul>
          </li>
        </ul>
      <% else %>
        <ul class="nav navbar-nav navbar-right user-nav">
          <li class="dropdown profile_menu">
          	<%#= link_to %>
            <% if !current_user.profile_pic_data.nil? %>
              <a href="#"><%= image_tag url_for(:action => 'show_image',:controller => "user_profile" , :id => current_user.id), :size => "32x32" %>
                <span>
                  <% if !current_user.first_name.blank? %>
                    <%= current_user.first_name%>&nbsp<%= current_user.last_name%>
                  <% else %>
                    <%= current_user.email %>
                  <% end %>
                </span></a>
            <% else %>
              <a href="#"><img alt="Avatar" src="/assets/avatar6.jpg" style="height: 30px;">
                <span>
                  <% if !current_user.first_name.blank? %>
                    <%= current_user.first_name%>&nbsp<%= current_user.last_name%>
                  <% else %>
                    <%= current_user.email %>
                  <% end %>
                </span>
              </a>
            <% end %>
          </li>
          <li>
            <%= link_to profile_path do %>
              <i class="fa fa-cogs"></i>
            <% end %>
          </li>
          <li>
            <%= link_to destroy_user_session_path, method: :delete do %>
              <i class = "fa fa-power-off"></i>
            <% end %>
          </li>
        </ul>
      <% end %> 
        <ul class="nav navbar-nav not-nav">
          <li>
            <%= link_to root_path, :style => "font-size: 30px" do %>
              <i class= "fa fa-home"></i>
            <% end %>
          </li>
        </ul> 
    </div>
  </div>
</div>
<script src="/assets/jPushMenu.js"></script>

app/views/layouts/shared/_generate_report.html.erb
<div class="content" id="report_tab">
  <div class="table-responsive">
    <div id="datatable_wrapper" class="dataTables_wrapper form-inline" role="grid">
      <table class="table table-bordered dataTable" id="datatable" aria-describedby="datatable_info">
        <thead>
          <tr role="row">
            <th class="sorting_asc" role="columnheader" tabindex="0" aria-controls="datatable" rowspan="1" colspan="1" aria-sort="ascending" style="width: 163px;" aria-label="Rendering engine: activate to sort column descending">Client Name</th>
            <th class="sorting" role="columnheader" tabindex="0" aria-controls="datatable" rowspan="1" colspan="1" style="width: 231px;" aria-label="Browser: activate to sort column ascending">Date</th>
            <th class="sorting" role="columnheader" tabindex="0" aria-controls="datatable" rowspan="1" colspan="1" style="width: 214px;" aria-label="Platform(s): activate to sort column ascending">Credit</th>
            <th class="sorting" role="columnheader" tabindex="0" aria-controls="datatable" rowspan="1" colspan="1" style="width: 137px;" aria-label="Engine version: activate to sort column ascending">Debit</th>
            <th class="sorting" role="columnheader" tabindex="0" aria-controls="datatable" rowspan="1" colspan="1" style="width: 127px;" aria-label="CSS grade: activate to sort column ascending">Outstanding</th>
          </tr>
        </thead>
        <tbody role="alert" aria-live="polite" aria-relevant="all" id="result">
        </tbody>
      </table>
    </div>
  </div>
  </div>

app/views/layouts/shared/_reports.html.erb
<div class="col-md-12" style="padding-left: 0px;">
  <div class="content">
    <div id="datatable_wrapper" class="dataTables_wrapper form-inline" role="grid">
      <%= form_tag generate_report_path, :remote => true do |f| %>
        <div class="form-group">
          <div class="form-group">
            <label>From</label><br/>
            <%= date_select(:date_from, 'written_on')  %>
            <%#= text_field_tag :date_from,nil , class: "form-control datetime" %>
            <%#= date_field_tag(:date_from, :autofocus => true)%>  
          </div>
          <div class="form-group">
            <label>To</label><br/>
            <%= date_select(:date_to, 'written_to', class: "form-control")  %>
          </div>
          <div class="form-group">
            <label>Client Name</label>
            <%= select_tag 'client_id', options_for_select(current_user.clients.collect{ |u| [u.client_name, u.id] }, :include_blank => true), { :class => "form-control" } %>
          </div>
          <div class="form-group">
            <label>Cash Type</label>
            <%= select_tag "cashflow_type", "<option>Both</option><option>Credit</option><option>Debit</option>".html_safe, { :class => "form-control" } %>
          </div>
        </div>
        <div class="form-group">
          <div class="col-sm-3">
            <label></label>
            <%= submit_tag "Generate Report", class: "btn btn-primary" %>
          </div>
        </div>
      <% end %>
    </div>     
  </div>
  <br/>
  <%= render :partial => "/layouts/shared/generate_report" %>
</div>

<style type="text/css">
#date_from_written_on_1i, #date_from_written_on_2i, #date_from_written_on_3i, #date_to_written_to_1i, #date_to_written_to_2i,#date_to_written_to_3i{
  height: 34px !important;
}
</style>
<script type="text/javascript">
  $(document).ready(function(){
     $(".datetime").datetimepicker({format: 'yyyy-mm-dd'});
  });
</script>

app/views/layouts/shared/_sidebar.html.erb
<div class="cl-sidebar">
  <div class="cl-toggle"><i class="fa fa-bars"></i></div>
  <div class="cl-navblock">
    <div class="menu-space">
      <div class="content">
        <div class="sidebar-logo">
          <div class="logo">
              <a href="index2.html"></a>
          </div>
        </div>
        <div class="side-user">
          <% if !current_user.profile_pic_data.nil? %>
            <div class="avatar"><%= image_tag url_for(:action => 'show_image', :controller => "user_profile" ,:id => current_user.id), :size => "50x50" %></div>
          <% else %>
            <div class="avatar"><img src="/assets/avatar6.jpg" alt="Avatar" style="height:50px;" /></div>  
          <% end %>
          <div class="info">
            <p>
              <% if !current_user.first_name.blank? %>
                <%= current_user.first_name %> <%= current_user.last_name %>
              <% else %>
                <%= current_user.email %>
              <% end %>
            </p>
          </div>
        </div>
        
        <!-- <div class="side-user">
          <ul class="cl-vnavigation">
            <li><%#= Cashflow.all.where(:cash_type => "Credit").sum(:amount) %> Credit</li>
            <li></li>
            <li></li>
        </ul>
        </div> -->
        <ul class="cl-vnavigation"><br/>
          <div class="col-sm-12 col-md-12">
            <div class="block-flat primary-box" style="padding: 0px 0px 0px 0px !important;">
              <div class="content">
                <table class="no-border">
                  <tbody >
                  <tr class="no-border-x no-border-y">
                    <td align="right">+ <%= @cr = current_user.cashflows.where(:cash_type => "Credit").sum(:amount) %> </td>
                    <td class="no-border">Credit</td>
                  </tr>
                  <tr class="no-border-y" style="background: none !important;">
                    <td align="right" class="no-border">- <%= @dr = current_user.cashflows.where(:cash_type => "Debit").sum(:amount) %> </td>
                    <td class="no-border">Debit</td>
                  </tr>
                  <tr class="no-border-x no-border-y" style="background: none !important;">
                    <% if @cr-@dr > 0 %>
                      <td align="right" class="no-border">+ <%= @cr - @dr %> </td>
                    <% elsif @cr-@dr < 0%>
                      <td align="right" class="no-border"><%= @cr - @dr %> </td>
                    <% else %>
                      <td align="right" class="no-border"> <%= @cr - @dr %> </td>
                    <% end %>
                    <td class="no-border">Outstanding</td>
                  </tr>
                  </tbody>
                </table>
              </div>
            </div>
          </div>
          <div class="col-sm-12 col-md-12">
            <div class="block-flat primary-box" style="padding: 0px 0px 0px 0px !important;">
              <div class="content">
                <p align="center"><%= link_to current_user.clients.count.to_s + " Clients", clients_path, :style => "color: #fff;" %> </p>
                <p align="center"><%= link_to current_user.cashflows.count.to_s + " Entries", cashflows_path, :style => "color: #fff;" %></p>
              </div>
            </div>
          </div><br/>
        </ul>
      </div>
    </div>
    
  </div>
</div>