config/routes.rb
AccountManager::Application.routes.draw do
  resources :cashflows
  resources :clients
  devise_for :users
  root :to => 'application#index'
  get 'show_image/:id' => 'user_profile#show_image'
  get 'user_profile/index'
  
  match '/setting' => "user_profile#edit", :as => :profile ,via: [:get, :patch]
  match 'profile/edit' => "user_profile#update", via: [ :put, :patch ], :as => :update_profile
  match 'profile/update_password'=> "user_profile#update_password", via: [:patch],:as => :update_password
  match 'profile/update_secret_password' => 'user_profile#update_secret_password', via: [:patch], :as => :update_secret_password

  match 'client_cash_flow_detail/:id' => "clients#cashflow_detail", via: [:get], :as => :cashflow_detail
  
  # Search route
  get 'search/new'
  match 'search/generate_report'=> "search#generate_report", via: [:post],:as => :generate_report


  match 'new_cashflow_credit'=>"cashflows#new",via: [:get],:as => :new_cashflow_credit
  match 'new_cashflow_debit'=>"cashflows#new",via: [:get],:as => :new_cashflow_debit


  #  Delete Validation Path
  match '/confirmation_secrate' => 'application#confirmation_secrate', :as => "confirmation", via: [:get]
  match '/confirmation_sec' => 'clients#confirmation_secrate', :as => "confirmation_cash", via: [:get]

  match '/confirmation_delete' => 'clients#confirmation_delete', :as => "confirmation_delete", via: [:get]
  match '/confirmation_cash_delete' => 'cashflows#confirmation_cash_delete', :as => "confirmation_cash_delete", via: [:get]

  
end

app/models/client.rb
class Client < ActiveRecord::Base
	has_many :cashflows, dependent: :destroy
	belongs_to :user
end

app/controllers/clients_controller.rb
class ClientsController < ApplicationController
  before_action :set_client, only: [:show, :edit, :update, :destroy, :cashflow_detail]

  # GET /clients
  # GET /clients.json
  def index
    @clients = current_user.clients.all
  end

  # GET /clients/1
  # GET /clients/1.json
  def show
  end
  
  def cashflow_detail
    @credit_amount = @client.cashflows.where(:cash_type => "Credit").sum(:amount)
    @debit_amount = @client.cashflows.where(:cash_type => "Debit").sum(:amount)
    @outstanding_amount = @credit_amount-@debit_amount
  end

  def confirmation_secrate
    @id = params[:id]
    @secrate = params[:secret_password]
    @secret_password = current_user.secret_password

    if @secrate == @secret_password
      @cashflow = Cashflow.find_by_id(@id)
      @cashflow.destroy
      flash[:notice] = " Successfully Deleted"
      redirect_to root_path
    else
      @cashflow = Cashflow.find_by_id(@id)
      @client = @cashflow.client.id
      flash[:error_notice]="Password was wrong."
      redirect_to cashflow_detail_path(@client)
    end
  end

  def confirmation_delete
    @id = params[:id]
    @secrate = params[:secret_password]
    @secret_password = User.first.secret_password

    if @secrate == @secret_password
      @client = Client.find_by_id(@id)
      @client.destroy
      flash[:notice] = "Successfully Deleted"
      redirect_to clients_path
    else
      flash[:error_notice]="Password was wrong."
      redirect_to clients_path
    end
  end

  # GET /clients/new
  def new
    @client = current_user.clients.new
  end

  # GET /clients/1/edit
  def edit
  end

  # POST /clients
  # POST /clients.json
  def create
    @client = current_user.clients.new(client_params)

    respond_to do |format|
      if @client.save
        format.html { redirect_to root_path, notice: 'Client was successfully created.' }
        format.json { render action: 'show', status: :created, location: @client }
      else
        format.html { render action: 'new' }
        format.json { render json: @client.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /clients/1
  # PATCH/PUT /clients/1.json
  def update
    respond_to do |format|
      if @client.update(client_params)
        format.html { redirect_to root_path, notice: 'Client was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @client.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /clients/1
  # DELETE /clients/1.json
  def destroy
    @client.destroy
    respond_to do |format|

      format.html { redirect_to root_path }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_client
      @client = Client.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def client_params
      params.require(:client).permit(:user_id, :client_name, :email, :phone_no, :city, :state, :country, :address)
    end
end

app/helpers/clients_helper.rb
module ClientsHelper
end

app/views/clients/_form.html.erb
<%= form_for @client, :html => { :id => "new_client" } do |f| %>
  <div class="form-group">
    <%= f.label :client_name %>
    <%= f.text_field :client_name, :placeholder=>"Enter Name", :class=>"form-control",:required => true  %>
  </div>
  <div class="form-group">
    <%= f.label :email %>
    <label>Email address</label> 
    <%= f.text_field :email, :required=>true, :email => true,:placeholder=> "Enter email",  :class=>"form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :phone_no %>
    <%= f.text_field :phone_no, :required => true, :number => true, :placeholder=>"Enter Phone Number", :class=>"form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :city %>
    <%= f.text_field :city, :placeholder=>"Enter City", :class=>"form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :state %>
    <%= f.text_field :state, :placeholder=>"Enter State", :class=>"form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :country %>
    <%= f.text_field :country, :placeholder=>"Enter Country", :class=>"form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :address %>
    <%= f.text_area :address, :placeholder=>"Enter Address", :class=>"form-control" %>
  </div>
  <button class="btn btn-primary" type="submit">Submit</button>
  <%= link_to "Cancel", root_path,:class=>"btn btn-default"  %>
<% end %>

<script type="text/javascript">
  $("#new_client").validate({
    rules: {
      client_name: {
        required: true
      },
      email: {
        required: true,
        email: true
      },
      phone_no: {
        required: true,
        number: true
      }
    }
  });
</script>
<style type="text/css">
.error {
  color: red;
}
</style>

app/views/clients/cashflow_detail.html.erb
<div class="cl-mcont">    
  <div class="row">
    <div class="col-sm-12 col-md-12">
      <div class="block-flat">
        <% if notice %>
          <div class="alert alert-danger">
            <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
              <i class="fa fa-times-circle sign"></i><strong>Error!</strong><%= notice %>
            </div>
          <% end %>
        <div class="header">              
          <h3><%= @client.client_name %></h3>
        </div>
        <div class="content">
          <div class="table-responsive">
            <div id="datatable_wrapper" class="dataTables_wrapper form-inline" role="grid">
              <table class="table table-bordered dataTable" id="datatable" aria-describedby="datatable_info">
                <thead>
                  <tr role="row">
                    <th class="sorting" role="columnheader" tabindex="0" aria-controls="datatable" rowspan="1" colspan="1" style="width: 231px;" aria-label="Browser: activate to sort column ascending">Date</th>
                    <th class="sorting" role="columnheader" tabindex="0" aria-controls="datatable" rowspan="1" colspan="1" style="width: 214px;" aria-label="Platform(s): activate to sort column ascending">Credit</th>
                    <th class="sorting" role="columnheader" tabindex="0" aria-controls="datatable" rowspan="1" colspan="1" style="width: 137px;" aria-label="Engine version: activate to sort column ascending">Debit</th>
                    <th class="sorting" role="columnheader" tabindex="0" aria-controls="datatable" rowspan="1" colspan="1" style="width: 127px;" aria-label="CSS grade: activate to sort column ascending">Outstanding</th>
                    <th class="sorting" role="columnheader" tabindex="0" aria-controls="datatable" rowspan="1" colspan="1" style="width: 127px;" aria-label="CSS grade: activate to sort column ascending">Action</th>
                  </tr>
                </thead>
                <tbody role="alert" aria-live="polite" aria-relevant="all">

                  <% @client.cashflows.each do |cashflow| %>
                    <tr class="gradeA odd">
                      <td class=" "><%= cashflow.date %></td>
                        <% if cashflow.cash_type == "Credit" %>
                          
                          <td class=" "> + <%= cashflow.amount %></td>
                          <td class=" "> -</td>
                          <td class=" "> + <%= cashflow.amount %></td>
                        <% else %>
                         
                          <td class=" "> -</td>
                          <td class=" "> - <%= cashflow.amount %></td>
                          <td class=" "> - <%= cashflow.amount %></td>
                        <% end %>
                      <td class=" ">
                          <a href="<%= edit_cashflow_path(cashflow) %>", class="btn-default"><i class="fa fa-edit"></i></a>
                          <a href="<%= cashflow_path(cashflow) %>", class="btn-default"><i class="fa fa-eye"></i></a>
                           <a href="#", data-toggle="modal" data-target="#md-default-<%= cashflow.id %>", class="btn-default"><i class="fa fa-times"></i></a> 
                          
                        </td>
                    </tr>
                    <div class="modal fade colored-header in" id="md-default-<%= cashflow.id %>" tabindex="-1" role="dialog">
                      <div class="modal-dialog">
                        <div class="modal-content">
                          <div class="modal-header">
                            <h3>Enter Your Secret secret_password</h3>
                            <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
                          </div>
                          <div class="modal-body">
                            <%= form_tag confirmation_cash_path, :method => 'get'  do %>
                              <div class="form-group">
                                <%= hidden_field_tag :id,{},:value=>cashflow.id%>
                                <label>Secret Password</label> : 
                                <%= password_field_tag :secret_password, :class=> "form-control"%>
                              </div>
                              <%= submit_tag "Submit", :class => "btn btn-primary btn-flat"%>
                            <% end %>
                          </div><!-- /.modal-content -->
                        </div><!-- /.modal-dialog -->
                      </div>
                    </div>
                  <%end  %> 
                  <tr class="gradeA odd">
                    <td class="center"> Total Summary</td>
                    <td class="center"> +<%= @credit_amount %></td>
                    <td class="center"> -<%= @debit_amount %></td>
                    <td class="center">
                      <% if @outstanding_amount > 0 %>
                        + <%= @outstanding_amount %>
                      <% elsif @outstanding_amount < 0 %>
                        <%= @outstanding_amount %>
                      <% else %>
                        <%= @outstanding_amount %>
                      <% end %>
                    </td>
                  </tr>
                </tbody>
              </table>
            </div>             
          </div>
        </div>
      </div>
    </div>        
  </div>
</div>
 
 

app/views/clients/edit.html.erb
<div class="cl-mcont">		
	<div class="row">
	  <div class="col-sm-6 col-md-6">
	    <div class="block-flat">
	      <div class="header">							
	        <h3>Edit Client</h3>
	      </div>
	      <div class="content">
	      	<%= render 'form' %>
	      </div>
	    </div>				
	  </div>
	</div>
</div>

app/views/clients/index.html.erb
<% if notice %>
  <div class="alert alert-success">
    <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
    <i class="fa fa-check sign"></i><strong>Success!</strong> <%= flash[:notice] %>
  </div>
<% elsif flash[:error_notice] %>
  <div class="alert alert-danger">
    <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
    <i class="fa fa-times-circle sign"></i><strong>Error!</strong> <%= flash[:error_notice] %>
  </div>
<% end %>
<div class="col-md-12" style="padding-left: 0px;">
  <div class="block-flat">
    <div class="header">              
      <h3>Client record <%= link_to "Add New Client", new_client_path, :style => "float: right;", :class=>"btn btn-primary btn-rad btn-trans" %></h3>
    </div>

    <div class="content">
      <div class="table-responsive">
        <table class="table table-bordered" id="datatable" >
          <thead>
            <tr>
              <th>Client Name</th>
              <th>Email</th>
              <th>Phone No.</th>
              
              <th>Action</th>
            </tr>
          </thead>
          <tbody>
            <% @clients.each do |client| %>
              <tr class="odd gradeX">
                <td><%= link_to client.client_name, client_path(client), :style => "color: #000;" %></td>
                <td><%= client.email %></td>
                <td><%= client.phone_no %></td>
                <td><a href="<%= edit_client_path(client) %>", class="btn-default"><i class="fa fa-edit"></i></a>
                    <a href="<%= client_path(client) %>", class="btn-default"><i class="fa fa-eye"></i></a>
                    <a href="#", data-toggle="modal" data-target="#md-default-<%= client.id %>", class="btn-default"><i class="fa fa-times"></i></a>
                </td>
                <div class="modal fade colored-header in" id="md-default-<%= client.id %>" tabindex="-1" role="dialog">
            <div class="modal-dialog">
              <div class="modal-content">
                <div class="modal-header">
                  <h3>Enter Your Secret secret_password</h3>
                  <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
                </div>
                <div class="modal-body">
                  <%= form_tag confirmation_delete_path, :method => 'get'  do %>
                    <div class="form-group">
                      <%= hidden_field_tag :id,{},:value=>client.id %>
                      <label>Secret Password</label> : 
                      <%= password_field_tag :secret_password, :class=> "form-control"%>
                    </div>
                    <%= submit_tag "Submit", :class => "btn btn-primary btn-flat"%>
                  <% end %>
                </div><!-- /.modal-content -->
              </div><!-- /.modal-dialog -->
            </div>
          </div>
              </tr>
            <% end %>
          </tbody>
        </table>              
      </div>
    </div>
  </div>        
</div>
  
<script type="text/javascript">
    
    $(document).ready(function(){
      //initialize the javascript
      //Basic Instance
      $("#datatable").dataTable();
      
      //Search input style
      $('.dataTables_filter input').addClass('form-control').attr('placeholder','Search');
      $('.dataTables_length select').addClass('form-control');    
          
       /* Formating function for row details */
        function fnFormatDetails ( oTable, nTr )
        {
            var aData = oTable.fnGetData( nTr );
            var sOut = '<table cellpadding="5" cellspacing="0" border="0" style="padding-left:50px;">';
            sOut += '<tr><td>Rendering engine:</td><td>'+aData[1]+' '+aData[4]+'</td></tr>';
            sOut += '<tr><td>Link to source:</td><td>Could provide a link here</td></tr>';
            sOut += '<tr><td>Extra info:</td><td>And any further details here (images etc)</td></tr>';
            sOut += '</table>';
             
            return sOut;
        }
       
        /*
         * Insert a 'details' column to the table
         */
        var nCloneTh = document.createElement( 'th' );
        var nCloneTd = document.createElement( 'td' );
        nCloneTd.innerHTML = '<img class="toggle-details" src="images/plus.png" />';
        nCloneTd.className = "center";
         
        $('#datatable2 thead tr').each( function () {
            this.insertBefore( nCloneTh, this.childNodes[0] );
        } );
         
        $('#datatable2 tbody tr').each( function () {
            this.insertBefore(  nCloneTd.cloneNode( true ), this.childNodes[0] );
        } );
         
        /*
         * Initialse DataTables, with no sorting on the 'details' column
         */
        var oTable = $('#datatable2').dataTable( {
            "aoColumnDefs": [
                { "bSortable": false, "aTargets": [ 0 ] }
            ],
            "aaSorting": [[1, 'asc']]
        });
         
        /* Add event listener for opening and closing details
         * Note that the indicator for showing which row is open is not controlled by DataTables,
         * rather it is done here
         */
        $('#datatable2').delegate('tbody td img','click', function () {
            var nTr = $(this).parents('tr')[0];
            if ( oTable.fnIsOpen(nTr) )
            {
                /* This row is already open - close it */
                this.src = "images/plus.png";
                oTable.fnClose( nTr );
            }
            else
            {
                /* Open this row */
                this.src = "images/minus.png";
                oTable.fnOpen( nTr, fnFormatDetails(oTable, nTr), 'details' );
            }
        } );
        
      $('.dataTables_filter input').addClass('form-control').attr('placeholder','Search');
      $('.dataTables_length select').addClass('form-control');    

    });
</script>

app/views/clients/new.html.erb
<div class="cl-mcont">		
	<div class="row">
	  <div class="col-sm-6 col-md-6">
	    <div class="block-flat">
	      <div class="header">							
	        <h3>New Client</h3>
	      </div>
	      <div class="content">
	      	<%= render 'form' %>
	      </div>
	    </div>				
	  </div>
	</div>
</div>

app/views/clients/show.html.erb
<div class="cl-mcont">    
  <div class="row">
    <div class="col-sm-6 col-md-6">
      <div class="block-flat">
        <div class="header">              
          <h3><%= @client.client_name %></h3>
        </div>
        <div class="content">
          <div class="form-group">
            <label>Email Address</label>
            <input type="text" readonly="readonly" class="form-control" value="<%= @client.email %>">
          </div>
          <div class="form-group">
            <label>Phone No.</label>
            <input type="text" readonly="readonly" class="form-control" value="<%= @client.phone_no %>">
          </div>
          <div class="form-group">
            <label>City</label>
            <input type="text" readonly="readonly" class="form-control" value="<%= @client.city %>">
          </div>
          <div class="form-group">
            <label>State</label>
            <input type="text" readonly="readonly" class="form-control" value="<%= @client.state %>">
          </div>
          <div class="form-group">
            <label>Country</label>
            <input type="text" readonly="readonly" class="form-control" value="<%= @client.country %>">
          </div>
          <div class="form-group">
            <label>Address</label>
            <input type="area" readonly="readonly" class="form-control" value="<%= @client. address%>">
          </div>
          <%= link_to 'Edit', edit_client_path(@client), :class=>"btn btn-primary" %>
          <%= link_to 'Cancel', root_url, :class=>"btn btn-default"  %>
        </div>
      </div>
    </div>        
  </div>
</div>
 