config/routes.rb
AccountManager::Application.routes.draw do
  resources :cashflows
  resources :clients
  devise_for :users
  root :to => 'application#index'
  get 'show_image/:id' => 'user_profile#show_image'
  get 'user_profile/index'
  
  match '/setting' => "user_profile#edit", :as => :profile ,via: [:get, :patch]
  match 'profile/edit' => "user_profile#update", via: [ :put, :patch ], :as => :update_profile
  match 'profile/update_password'=> "user_profile#update_password", via: [:patch],:as => :update_password
  match 'profile/update_secret_password' => 'user_profile#update_secret_password', via: [:patch], :as => :update_secret_password

  match 'client_cash_flow_detail/:id' => "clients#cashflow_detail", via: [:get], :as => :cashflow_detail
  
  # Search route
  get 'search/new'
  match 'search/generate_report'=> "search#generate_report", via: [:post],:as => :generate_report


  match 'new_cashflow_credit'=>"cashflows#new",via: [:get],:as => :new_cashflow_credit
  match 'new_cashflow_debit'=>"cashflows#new",via: [:get],:as => :new_cashflow_debit


  #  Delete Validation Path
  match '/confirmation_secrate' => 'application#confirmation_secrate', :as => "confirmation", via: [:get]
  match '/confirmation_sec' => 'clients#confirmation_secrate', :as => "confirmation_cash", via: [:get]

  match '/confirmation_delete' => 'clients#confirmation_delete', :as => "confirmation_delete", via: [:get]
  match '/confirmation_cash_delete' => 'cashflows#confirmation_cash_delete', :as => "confirmation_cash_delete", via: [:get]

  
end

app/models/cashflow.rb
class Cashflow < ActiveRecord::Base
	belongs_to :client
	belongs_to :user
	validates :cash_type, :client_id, presence: true

end

app/controllers/cashflows_controller.rb
class CashflowsController < ApplicationController
  before_action :set_cashflow, only: [:show, :edit, :update, :destroy]

  # GET /cashflows
  # GET /cashflows.json
  def index
    @cashflows = current_user.cashflows.all
  end

  # GET /cashflows/1
  # GET /cashflows/1.json
  def show
  end

  def confirmation_cash_delete
    @id = params[:id]
    @secrate = params[:secret_password]
    @secret_password = current_user.secret_password

    if @secrate == @secret_password
      @cashflow = Cashflow.find_by_id(@id)
      @cashflow.destroy
      flash[:notice] = "Successfully Deleted"
      redirect_to cashflows_path
    else
      @cashflow = Cashflow.find_by_id(@id)
      @client = @cashflow.client.id
      flash[:error_notice]="Password was wrong."
      redirect_to cashflows_path
    end
  end

  # GET /cashflows/new
  def new
    @cashflow = current_user.cashflows.new
  end

  # GET /cashflows/1/edit
  def edit
  end

  # POST /cashflows
  # POST /cashflows.json
  def create
    @cashflow = current_user.cashflows.new(cashflow_params)

    respond_to do |format|
      if @cashflow.save
        format.html { redirect_to root_path, notice: 'Cashflow was successfully created.' }
        format.json { render action: 'show', status: :created, location: @cashflow }
      else
        format.html { render action: 'new' }
        format.json { render json: @cashflow.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /cashflows/1
  # PATCH/PUT /cashflows/1.json
  def update
    respond_to do |format|
      if @cashflow.update(cashflow_params)
        format.html { redirect_to root_path, notice: 'Cashflow was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @cashflow.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /cashflows/1
  # DELETE /cashflows/1.json
  def destroy
    @cashflow.destroy
    respond_to do |format|
      format.html { redirect_to cashflows_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_cashflow
      @cashflow = Cashflow.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def cashflow_params
      params.require(:cashflow).permit(:user_id, :cash_type, :date, :amount, :description, :client_id)
    end
end

app/helpers/cashflows_helper.rb
module CashflowsHelper
end

app/views/cashflows/_credit_form.html.erb
<div class="form-group">
  <%= f.label :cash_type %>
  <div class="radio">
    credit <%= f.radio_button :cash_type, "Credit",:required => true,:checked=>true%> <br>
    debit <%= f.radio_button :cash_type, "Debit",:required => true%> 
  </div> 
</div>

app/views/cashflows/_debit_form.html.erb
<div class="form-group">
	<%= f.label :cash_type %>
  <div class="radio">
    Credit <%= f.radio_button :cash_type, "Credit",:required => true%> <br>
    Debit <%= f.radio_button :cash_type, "Debit",:required => true, :checked=> true %> 
  </div>
</div>

app/views/cashflows/_form.html.erb
<%= form_for @cashflow, :html => { :id => "new_cashflow" } do |f| %>
  <div class="form-group">
    <%= f.label :client_id, "Client Name"  %>
    <%= f.collection_select(:client_id,current_user.clients.all,:id,:client_name,{:include_blank => " " }, :required => true ,:autofocus => true,:class => "form-control")%><br/> <%= link_to "( Add New Client )", new_client_path %>
  </div>
  <div class="form-group">
    <%if request.path == "/new_cashflow_credit" %>
      <%= render "credit_form",:f=>f %>
    <% elsif request.path == "/new_cashflow_debit"%>
      <%= render "debit_form",:f=>f %>
    <% else %>
      <%= f.label :cash_type %>
        <% ["Credit", "Debit"].each do |a| %>
        <div class="radio">
          <%= a %><%= f.radio_button :cash_type, a,:required => true%> 
        </div>
      <% end %>
    <% end %>
  </div>
  <div class="form-group">
    <%= f.label :date %><br/>
    <%= f.date_select(:date, :start_year => 1980 ,:required => true)%>
  </div>
  <div class="form-group">
    <%= f.label :amount %>
    <%= f.text_field :amount,:required => true, :number => true, :placeholder=>"Enter Amount", :class=>"form-control"%> 
  </div>
  <div class="form-group">
    <%= f.label :description %>
    <%= f.text_area :description, :placeholder=>"Enter Description", :class=>"form-control" %>
  </div>
   <button class="btn btn-primary" type="submit">Submit</button>
  <%= link_to "Cancel", root_path,:class=>"btn btn-default"  %>
<% end %>
<script type="text/javascript">
  $("#new_cashflow").validate({
    rules: {
      client_id: {
        required: true
      },
      cash_type: {
        required: true
      },
      date: {
        required: true
      },
      amount: {
        required: true,
        number: true
      }
    }
  });
</script>
<style type="text/css">
.error {
  color: red;
}
#cashflow_date_1i, #cashflow_date_2i, #cashflow_date_3i{
  width: 32%;
  height: 34px;
}
</style>

app/views/cashflows/edit.html.erb
<div class="cl-mcont">		
	<div class="row">
	  <div class="col-sm-6 col-md-6">
	    <div class="block-flat">
	      <div class="header">							
	        <h3> Edit Cash Flow</h3>
	      </div>
	      <div class="content">
	      	<%= render 'form' %>
	      </div>
	    </div>				
	  </div>
	</div>
</div>

app/views/cashflows/index.html.erb
<% if notice %>
  <div class="alert alert-success">
    <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
    <i class="fa fa-check sign"></i><strong>Success!</strong> <%= flash[:notice] %>
  </div>
<% elsif flash[:error_notice] %>
  <div class="alert alert-danger">
    <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
    <i class="fa fa-times-circle sign"></i><strong>Error!</strong> <%= flash[:error_notice] %>
  </div>
<% end %>

<div class="col-md-12" style="padding-left: 0px;">
  <div class="block-flat">
    <div class="header">              
      <h3>Cashflow Record <%= link_to 'Add New Cashflow', new_cashflow_path, :style => "float: right;", :class=>"btn btn-primary btn-rad btn-trans" %></h3>
    </div>

    <div class="content">
      <div class="table-responsive">
        <table class="table table-bordered" id="datatable" >
          <thead>
            <tr>
              <th>Client Name</th>
              <th>Cash Type</th>
              <th>Date</th>
              <th>Amount</th>
              <th>Action</th>
            </tr>
          </thead>
          <tbody>
            <% @cashflows.each do |cashflow| %>
              <tr class="odd gradeX">
                <td><%= cashflow.client.client_name %></td>
                <td><%= cashflow.cash_type %></td>
                <td><%= cashflow.date %></td>
                <td><%= cashflow.amount %></td>
                <td><a href="<%= edit_cashflow_path(cashflow) %>", class="btn-default"><i class="fa fa-edit"></i></a>
                    <a href="<%= cashflow_path(cashflow) %>", class="btn-default"><i class="fa fa-eye"></i></a>
                    <a href="#", data-toggle="modal" data-target="#md-default-<%= cashflow.id %>", class="btn-default"><i class="fa fa-times"></i></a>
                </td>
              </tr>
              <div class="modal fade colored-header in" id="md-default-<%= cashflow.id %>" tabindex="-1" role="dialog">
                  <div class="modal-dialog">
                    <div class="modal-content">
                      <div class="modal-header">
                        <h3>Enter Your Secret secret_password</h3>
                        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
                      </div>
                      <div class="modal-body">
                        <%= form_tag confirmation_cash_delete_path, :method => 'get'  do %>
                          <div class="form-group">
                            <%= hidden_field_tag :id,{},:value=>cashflow.id%>
                            <label>Secret Password</label> : 
                            <%= password_field_tag :secret_password, :class=> "form-control"%>
                          </div>
                          <%= submit_tag "Submit", :class => "btn btn-primary btn-flat"%>
                        <% end %>
                      </div><!-- /.modal-content -->
                    </div><!-- /.modal-dialog -->
                  </div>
                </div>
            <% end %>
          </tbody>
        </table>              
      </div>
    </div>
  </div>        
</div>
<style type="text/css">
.paginate_disabled_previous{
  margin-right: 30px;
}
</style>
<script type="text/javascript">
    
    $(document).ready(function(){
      //initialize the javascript
      //Basic Instance
      $("#datatable").dataTable();
      
      //Search input style
      $('.dataTables_filter input').addClass('form-control').attr('placeholder','Search');
      $('.dataTables_length select').addClass('form-control');    
          
       /* Formating function for row details */
        function fnFormatDetails ( oTable, nTr )
        {
            var aData = oTable.fnGetData( nTr );
            var sOut = '<table cellpadding="5" cellspacing="0" border="0" style="padding-left:50px;">';
            sOut += '<tr><td>Rendering engine:</td><td>'+aData[1]+' '+aData[4]+'</td></tr>';
            sOut += '<tr><td>Link to source:</td><td>Could provide a link here</td></tr>';
            sOut += '<tr><td>Extra info:</td><td>And any further details here (images etc)</td></tr>';
            sOut += '</table>';
             
            return sOut;
        }
       
        /*
         * Insert a 'details' column to the table
         */
        var nCloneTh = document.createElement( 'th' );
        var nCloneTd = document.createElement( 'td' );
        nCloneTd.innerHTML = '<img class="toggle-details" src="images/plus.png" />';
        nCloneTd.className = "center";
         
        $('#datatable2 thead tr').each( function () {
            this.insertBefore( nCloneTh, this.childNodes[0] );
        } );
         
        $('#datatable2 tbody tr').each( function () {
            this.insertBefore(  nCloneTd.cloneNode( true ), this.childNodes[0] );
        } );
         
        /*
         * Initialse DataTables, with no sorting on the 'details' column
         */
        var oTable = $('#datatable2').dataTable( {
            "aoColumnDefs": [
                { "bSortable": false, "aTargets": [ 0 ] }
            ],
            "aaSorting": [[1, 'asc']]
        });
         
        /* Add event listener for opening and closing details
         * Note that the indicator for showing which row is open is not controlled by DataTables,
         * rather it is done here
         */
        $('#datatable2').delegate('tbody td img','click', function () {
            var nTr = $(this).parents('tr')[0];
            if ( oTable.fnIsOpen(nTr) )
            {
                /* This row is already open - close it */
                this.src = "images/plus.png";
                oTable.fnClose( nTr );
            }
            else
            {
                /* Open this row */
                this.src = "images/minus.png";
                oTable.fnOpen( nTr, fnFormatDetails(oTable, nTr), 'details' );
            }
        } );
        
      $('.dataTables_filter input').addClass('form-control').attr('placeholder','Search');
      $('.dataTables_length select').addClass('form-control');    

    });
</script>

app/views/cashflows/new.html.erb
<div class="cl-mcont">		
	<div class="row">
	  <div class="col-sm-6 col-md-6">
	    <div class="block-flat">
	      <div class="header">							
	        <h3>Cash Flow</h3>
	      </div>
	      <div class="content">
	      	<%= render 'form' %>
	      </div>
	    </div>				
	  </div>
	</div>
</div>

app/views/cashflows/show.html.erb
<div class="cl-mcont">    
  <div class="row">
    <div class="col-sm-6 col-md-6">
      <div class="block-flat">
        <div class="header">              
          <h3>Cash Flow</h3>
        </div>
        <div class="content">
          <div class="form-group">
            <label>Client Name</label>
            <input type="text" readonly="readonly" class="form-control" value="<%= @cashflow.client.client_name %>">
          </div>
          <div class="form-group">
            <label>Cash Type</label>
            <input type="text" readonly="readonly" class="form-control" value="<%= @cashflow.cash_type %>">
          </div>
          <div class="form-group">
            <label>Date</label>
            <input type="text" readonly="readonly" class="form-control" value="<%= @cashflow.date %>">
          </div>
          <div class="form-group">
            <label>Amount</label>
            <input type="text" readonly="readonly" class="form-control" value="<%= @cashflow.amount %>">
          </div>
          <div class="form-group">
            <label>Description</label>
            <input type="text" readonly="readonly" class="form-control" value="<%= @cashflow.description %>">
          </div>
          <%= link_to 'Edit', edit_cashflow_path(@cashflow), :class=>"btn btn-primary" %>
          <%= link_to 'Back', root_url, :class=>"btn btn-default"  %>
        </div>
      </div>
    </div>        
  </div>
</div>