config/routes.rb
AccountManager::Application.routes.draw do
  resources :cashflows
  resources :clients
  devise_for :users
  root :to => 'application#index'
  get 'show_image/:id' => 'user_profile#show_image'
  get 'user_profile/index'
  
  match '/setting' => "user_profile#edit", :as => :profile ,via: [:get, :patch]
  match 'profile/edit' => "user_profile#update", via: [ :put, :patch ], :as => :update_profile
  match 'profile/update_password'=> "user_profile#update_password", via: [:patch],:as => :update_password
  match 'profile/update_secret_password' => 'user_profile#update_secret_password', via: [:patch], :as => :update_secret_password

  match 'client_cash_flow_detail/:id' => "clients#cashflow_detail", via: [:get], :as => :cashflow_detail
  
  # Search route
  get 'search/new'
  match 'search/generate_report'=> "search#generate_report", via: [:post],:as => :generate_report


  match 'new_cashflow_credit'=>"cashflows#new",via: [:get],:as => :new_cashflow_credit
  match 'new_cashflow_debit'=>"cashflows#new",via: [:get],:as => :new_cashflow_debit


  #  Delete Validation Path
  match '/confirmation_secrate' => 'application#confirmation_secrate', :as => "confirmation", via: [:get]
  match '/confirmation_sec' => 'clients#confirmation_secrate', :as => "confirmation_cash", via: [:get]

  match '/confirmation_delete' => 'clients#confirmation_delete', :as => "confirmation_delete", via: [:get]
  match '/confirmation_cash_delete' => 'cashflows#confirmation_cash_delete', :as => "confirmation_cash_delete", via: [:get]

  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  
  
  before_filter :authenticate_user!


  def index
    session[:client_id] = nil
    session[:cashflow_id] = nil

  	@total_credit = current_user.cashflows.where(:cash_type => "Credit").sum(:amount)
  	@total_debit = current_user.cashflows.where(:cash_type => "Debit").sum(:amount)
  	@outstanding = @total_credit - @total_debit
  end


  def confirmation_secrate
    @id = params[:id]
    @secrate = params[:secret_password]
    @secret_password = current_user.secret_password

    if @secrate == @secret_password
      @client = Client.find_by_id(@id)
      @client.destroy
      flash[:notice] = "Successfully Deleted"
      logger.info "<------------#{request.path}-------------------->"
      redirect_to root_path
    else
      flash[:error_notice]="Password was wrong."
      redirect_to root_path
    end
  end
  private
    def mobile_device?
      request.user_agent =~ /Mobile|webOS/
    end
    helper_method :mobile_device?
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/application/_cashflow_deatil.html.erb
<h3><%= link_to "Add Credit", new_cashflow_credit_path, :class => "btn btn-primary btn-rad btn-trans" %><%= link_to "Add Debit", new_cashflow_debit_path, :class => "btn btn-primary btn-rad btn-trans" %></h3>
<div class="col-md-12" style="padding-left: 0px;">
    <div class="content">
      <div class="table-responsive">
        <div id="datatable_wrapper" class="dataTables_wrapper form-inline" role="grid">         
          <table class="table table-bordered" id="datatable2" >
            <thead>
              <tr>
                <th>Client Name</th>
                <th>Date</th>
                <th>Credit</th>
                <th>Debit</th>
                <th>Outstanding</th>
                <th>Action</th>
              </tr>
            </thead>
            <tbody>
              <% current_user.clients.each do |client| %>
                <% @credit = 0 %>
                <% @debit = 0 %>
                <% if client.cashflows.count > 0 %>
                  <tr class="odd gradeX">
                    <td><%= client.client_name %></td>
                    <td><%= client.cashflows.last.date %></td>
                    <% client.cashflows.each do | cashflow|  %>
                      <% if cashflow.cash_type == "Credit" %>
                        <% @credit += cashflow.amount  %>
                      <% else %>
                        <% @debit += cashflow.amount %>
                      <% end %>
                    <% end %>
                      <td class="gcredit"> + <%= @credit %></td>
                      <td class="rdebit"> - <%= @debit %></td>
                      <% if @credit-@debit > 0  %>
                        <td class="gcredit"> + <%= @credit - @debit %></td>
                      <% elsif @credit-@debit < 0 %>
                        <td class="rdebit">  <%= @credit - @debit %></td>
                      <% else %>
                        <td>  <%= @credit - @debit %> </td>
                      <% end %>
                    <td>
                      <a href="<%= cashflow_detail_path(client) %>", class="btn-default"><i class="fa fa-eye"></i> View</a>  
                    </td>
                  </tr>
                <%end  %> 
              <% end %>
              <tr class="gradeA odd">
                <td colspan="2" > Total Summary</td>
                <td class="gcredit"> + <%= @total_credit %></td>
                <td class="rdebit"> -<%= @total_debit %></td>
                <% if @outstanding > 0 %>
                  <td style="color: green;">  + <%= @outstanding %> </td>
                  <% elsif @outstanding < 0 %>
                  <td class="rdebit"> <%= @outstanding %> </td>
                  <% else %>
                  <td><%= @outstanding %></td>
                  <% end %>
                </td>
              </tr>
            </tbody>
          </table>
        </div>             
      </div>
    </div> 
</div>
<script type="text/javascript" src="/assets/jquery.datatables.min.js"></script>
<script type="text/javascript">
      //Add dataTable Functions
    
    $(document).ready(function(){
      //initialize the javascript
      //Basic Instance
      $("#datatable").dataTable();
      
      //Search input style
      $('.dataTables_filter input').addClass('form-control').attr('placeholder','Search');
      $('.dataTables_length select').addClass('form-control');    
          
       /* Formating function for row details */
        function fnFormatDetails ( oTable, nTr )
        {
            var aData = oTable.fnGetData( nTr );
            var sOut = '<table cellpadding="5" cellspacing="0" border="0" style="padding-left:50px;">';
            sOut += '<tr><td>Client Name:</td><td>'+aData[1]+' '+aData[4]+'</td></tr>';
            sOut += '<tr><td>Credit:</td><td>Could provide a link here</td></tr>';
            sOut += '<tr><td>Debit:</td><td>And any further details here (images etc)</td></tr>';
            sOut += '</table>';
             
            return sOut;
        }
       
         
        $('#datatable2 thead tr').each( function () {
            this.insertBefore( nCloneTh, this.childNodes[0] );
        } );
         
        $('#datatable2 tbody tr').each( function () {
            this.insertBefore(  nCloneTd.cloneNode( true ), this.childNodes[0] );
        } );
         
        /*
         * Initialse DataTables, with no sorting on the 'details' column
         */
        var oTable = $('#datatable2').dataTable( {
            "aoColumnDefs": [
                { "bSortable": false, "aTargets": [ 0 ] }
            ],
            "aaSorting": [[1, 'asc']]
        });
         
        /* Add event listener for opening and closing details
         * Note that the indicator for showing which row is open is not controlled by DataTables,
         * rather it is done here
         */
        $('#datatable2').delegate('tbody td img','click', function () {
            var nTr = $(this).parents('tr')[0];
            if ( oTable.fnIsOpen(nTr) )
            {
                /* This row is already open - close it */
                
                oTable.fnClose( nTr );
            }
            else
            {
                /* Open this row */
                oTable.fnOpen( nTr, fnFormatDetails(oTable, nTr), 'details' );
            }
        } );
        
      $('.dataTables_filter input').addClass('form-control').attr('placeholder','Search');
      $('.dataTables_length select').addClass('form-control');    

    });
</script>

app/views/application/_client_detail.html.erb
<h3><%= link_to "Add New Client", new_client_path, :class => "btn btn-primary btn-rad btn-trans" %></h3>
<div class="col-md-12" style="padding-left: 0px;">
    <div class="content">
      <div class="table-responsive">
        <div id="" class="dataTables_wrapper form-inline" role="grid">
          
          <table class="table table-bordered dataTable" id="datatable" aria-describedby="datatable_info">
            <thead>
              <tr role="row">
                <th class="sorting_asc" role="columnheader" tabindex="0" aria-controls="datatable" rowspan="1" colspan="1" aria-sort="ascending" style="width: 163px;" aria-label="Rendering engine: activate to sort column descending">Client Name</th>
                <th class="sorting" role="columnheader" tabindex="0" aria-controls="datatable" rowspan="1" colspan="1" style="width: 127px;" aria-label="CSS grade: activate to sort column ascending">Phone Number</th>
                <th class="sorting" role="columnheader" tabindex="0" aria-controls="datatable" rowspan="1" colspan="1" style="width: 127px;" aria-label="CSS grade: activate to sort column ascending">Actions</th>
              </tr>
            </thead>
            <tbody role="alert" aria-live="polite" aria-relevant="all">
              <% current_user.clients.each do |client| %>
              <tr class="gradeA odd">
                <td class=" sorting_1"><%= link_to client.client_name, client_path(client), :style => "color: #000;" %></td>
                <td class="center "> <%= client.phone_no %> </td>
                <td class=" ">
                  <a href="<%= edit_client_path(client) %>", class="btn-default"><i class="fa fa-edit"></i></a>
                  <a href="<%= client_path(client) %>", class="btn-default"><i class="fa fa-eye"></i></a>
                  <a href="#", data-toggle="modal" data-target="#md-default-<%= client.id %>", class="btn-default"><i class="fa fa-times"></i></a> 
                  <!-- <button  data-target="#md-default-<%= client.id %>" type="button" class="btn btn-primary btn-flat"> Default</button> -->
                </td>
              </tr>
              <div class="modal fade colored-header in" id="md-default-<%= client.id %>" tabindex="-1" role="dialog">
                <div class="modal-dialog">
                  <div class="modal-content">
                    <div class="modal-header">
                      <h3>Enter Your Secret secret_password</h3>
                      <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
                    </div>
                    <div class="modal-body">
                      <%= form_tag confirmation_path, :method => 'get'  do %>
                        <div class="form-group">
                          <%= hidden_field_tag :id,{},:value=>client.id %>
                          <label>Secret Password</label> : 
                          <%= password_field_tag :secret_password, :class=> "form-control"%>
                        </div>
                        <%= submit_tag "Submit", :class => "btn btn-primary btn-flat"%>
                      <% end %>
                    </div><!-- /.modal-content -->
                  </div><!-- /.modal-dialog -->
                </div>
              </div>
              <% end %>
            </tbody>
          </table>
        </div>             
      </div>
    </div>        
  </div>

app/views/application/index.html.erb
<% if notice %>
  <div class="alert alert-success">
    <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
    <i class="fa fa-check sign"></i><strong>Success!</strong> <%= flash[:notice] %>
  </div>
<% elsif flash[:error_notice] %>
  <div class="alert alert-danger">
    <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
    <i class="fa fa-times-circle sign"></i><strong>Error!</strong> <%= flash[:error_notice] %>
  </div>
<% end %>
<div class="cl-mcont">    
  <div class="row">   
    <div class="col-sm-12 col-md-12" style="padding-left: 0px;">
      <div class="tab-container" style="margin-top: -35px;">
        <ul class="nav nav-tabs">
          <li class=""><a href="#client" data-toggle="tab">Clients</a></li>
          <li class="active"><a href="#cashflow" data-toggle="tab">Cash Flow</a></li>
          <li class=""><a href="#messages" data-toggle="tab">Reports</a></li>
        </ul>
        <div class="tab-content">
          <div class="tab-pane cont" id="client">
            <%= render :partial => "/application/client_detail" %>
          </div>
          <div class="tab-pane active" id="cashflow">
            <%= render :partial => "/application/cashflow_deatil" %>
          </div>
          <div class="tab-pane" id="messages">
            <%= render :partial => "/layouts/shared/reports" %>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>